server:
  port: 8033

spring:
  application:
    name: consumer-demo-3
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      type: simple
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: false